### ISSUE TITLE
PowerShell: Line prompt is replaces with only a greater than character

### ISSUE THREAD

**Issue by philibertperusse** [microsoft/inshellisense#10]
The default powershell line prompt is:
  `PS [CurrentDirectory]> `
When running inshellisense, this gets replaces with
 `> `

And the line prompt no longer shows the CurrentDirectory

**Comment by JosefSaltz** [comment]
I'm also seeing this behavior for bash

**Comment by MystPi** [comment]
I think this was intended... however, I find it quite hard to use and would like an option to revert back to the normal prompt.

**Comment by chrisgrieser** [comment]
Seems to happen in every shell. I also experience this using zsh.

For people who use custom prompts like [Starship](https://starship.rs/), this is kind of a dealbreaker, since the custom prompt is basically removed. Also, any kind of syntax highlighting via [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting), is apparently also gone

**Comment by cpendery** [comment]
I'm working on better supporting the underlying shells so syntax highlighting, `cd`, & custom prompts all work

**Comment by cpendery** [comment]
Closing as this was fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)
