### ISSUE TITLE
My little wish?

### ISSUE THREAD

**Issue by dvlpr91** [microsoft/inshellisense#283]
Awkward for existing user experience.

For example, there are currently only three files in my path: `asdqwe`, `asdasd`, and `asdzxc`.

I usually type up to `a` or `as` and hit tab.

What I expect is that it will autocomplete up to `asd`, which is what the 3 files have in common.

After that, I expect to type one more character or use the keyboard cursor in the tooltip to get to where I want to go and hit tab.

As a result, when I first type up to `a`, I expect to see not only `asdqwe`, `asdasd`, and `asdzxc` in the tooltip, but I also expect to be able to select an autocomplete like `asd-` as the first element.

**Comment by cpendery** [comment]
While this fits with the experience some users are used to for bash, with other shells like `fish` or `nushell`, once the completion is visible, selecting tab will do the full completion. This is the same with an editor like VSCode. Since inshellisense is trying to emulate these experiences, I don't think it makes sense to only apply part of a user's accepted suggestion
